comparators:
  # Tabular files (CSV, TSV etc.)
  "*_mqc.tsv":
    type: tabular
    abs_tol: 1e-6
    rel_tol: 0.01
    comment: "#"

  "*.csv":
    type: tabular
    abs_tol: 1e-3
    rel_tol: 0.01
    check_column_order: false

  "*.tsv":
    type: tabular
    abs_tol: 1
    rel_tol: 0.01
    comment: "#"

  # Images
  "*.png":
    type: image
    method: pixel
    tolerance: 0.01

  "*.jpg":
    type: image
    method: pixel
    tolerance: 0.01

  # HDF5
  "*.h5":
    type: hdf5
    tolerance: 1e-6

  "*.hdf5":
    type: hdf5
    tolerance: 1e-6

  # Bioinformatics
  "*.fasta":
    type: fasta

  "*.fa":
    type: fasta

  "*.bam":
    type: bam

  "*.vcf":
    type: vcf


  # Fallback for anything else
  "*.bin":
    type: binary

exclude_extensions: 
- ".pdf"
- ".txt"
- ".log"
- ".out"
- ".idxstats"
- ".stats"
- ".gtf"
- ".xls"
- ".ctab"
- ".r"
- ".bai"
- ".html"